[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc-version = "0.8.20"

# Remappings
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

# Optimizer settings
optimizer = true
optimizer_runs = 200

# Gas settings
gas_limit = 9223372036854775807
gas_price = 20000000000

# Test settings
verbosity = 2

[rpc_endpoints]
mainnet = "${BASE_MAINNET_RPC}"
sepolia = "${SEPOLIA_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }